scr/AGS.ERP.Web/Controllers/ClienteController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AGS.ERP.Application.Interfaces;
using AGS.ERP.Application.ViewModel;

namespace AGS.ERP.Web.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteAppService _clienteAppService;
        private readonly IEstadoAppService _estadoAppService;
        private readonly ICidadeAppService _cidadeAppService;
        private readonly IEnderecoAppService _enderecoAppService;

        public ClienteController(IClienteAppService clienteAppService,
                                 IEstadoAppService estadoAppService,
                                 ICidadeAppService cidadeAppService,
                                 IEnderecoAppService enderecoAppService
            )
        {
            _clienteAppService = clienteAppService;
            _estadoAppService = estadoAppService;
            _cidadeAppService = cidadeAppService;
            _enderecoAppService = enderecoAppService;
        }

        // GET: Cliente
        public IActionResult Index()
        {
            return View(_clienteAppService.GetAll());
        }

        // GET: Cliente/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _clienteAppService.GetById((int)id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Cliente/Create
        public IActionResult Create()
        {
            ViewBag.ClienteId = "0";
            ViewBag.UF = new SelectList(_estadoAppService.GetAll().OrderBy(e => e.UF), "UF", "Nome");
            ViewBag.CidadeId = new SelectList(_cidadeAppService.GetAll().OrderBy(e => e.UF), "CidadeId", "Nome");
            ViewBag.TipoEndereco = new SelectList(Enum.GetValues(typeof(TipoEnderecoViewModel)));
            return View();
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Create(ClienteEnderecoViewModel cliente)
        {
            string erroMensagem = "";


            if (!ModelState.IsValid)
            {
                foreach (var item in ModelState.Values.SelectMany(v => v.Errors).ToList())
                {
                    erroMensagem += string.Format("{0}<br>", item.ErrorMessage);
                }

                return BadRequest(erroMensagem);
            }

            
            var clienteResult = _clienteAppService.Add(cliente);
            //return RedirectToAction(nameof(Index));

            if (clienteResult.IsValid)
            {
                ViewBag.ClienteId = cliente.ClienteId.ToString();
                return Json(new { ClienteId = cliente.ClienteId });
            }
            else{
                foreach (var item in clienteResult.Erros.OrderBy(e => e.Message))
                {
                    erroMensagem += string.Format("{0}<br>", item.Message);
                }

                return BadRequest(erroMensagem);
            }

        }


        // GET: Cliente/Edit/5
        public IActionResult Edit(int? id)
        {
            string erroMensagem = "";
            if (id == null)
            {
                return NotFound("Id não encontrado para atualização");
            }

            var cliente = _clienteAppService.GetById((int)id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ClienteViewModel cliente)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _clienteAppService.Update(cliente);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _clienteAppService.GetById(id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var cliente = _clienteAppService.GetById(id);

            if (cliente == null)
            {
                return NotFound();
            }
            _clienteAppService.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            //TODO: Melhorar metodo
            return !string.IsNullOrEmpty(_clienteAppService.GetById(id).ClienteId.ToString());
        }

        public JsonResult GetStateByCity(int idCidade)
        {
            //var estado = _estadoAppService.GetByUF(_cidadeAppService.GetById(idCidade).UF);
            var estado = _cidadeAppService.GetById(idCidade).UF;
            return Json(estado);
        }

        public IActionResult EnderecoCliente(int id)
        {

            var enderecos = _enderecoAppService.ObterEnderecoPorCliente(id);
            //var enderecos = _clienteAppService.ClienteCompleto(id).Endereco;

            return PartialView(enderecos);
        }
    }
}

scr/AGS.ERP.Web/Controllers/FornecedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AGS.ERP.Domain.Entities;
using AGS.ERP.Infra.Data.Context;
using AGS.ERP.Application.Interfaces;
using AGS.ERP.Application.ViewModel;

namespace AGS.ERP.Web.Controllers
{
    public class FornecedoresController : Controller
    {
        private readonly IFornecedorAppService _fornecedorAppService;

        public FornecedoresController(IFornecedorAppService fornecedorAppService)
        {
            _fornecedorAppService = fornecedorAppService;
        }

        // GET: Fornecedores
        public IActionResult Index()
        {
            return View(_fornecedorAppService.GetAll());
        }

        // GET: Fornecedores/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = _fornecedorAppService.GetById(id);
                
            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }

        // GET: Fornecedores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fornecedores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FornecedorViewModel fornecedor)
        {
            if (ModelState.IsValid)
            {
                _fornecedorAppService.Add(fornecedor);
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedor);
        }

        // GET: Fornecedores/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = _fornecedorAppService.GetById(id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            return View(fornecedor);
        }

        // POST: Fornecedores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, FornecedorViewModel fornecedor)
        {
            if (id != fornecedor.FornecedorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _fornecedorAppService.Update(fornecedor);                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FornecedorExists(fornecedor.FornecedorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedor);
        }

        // GET: Fornecedores/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = _fornecedorAppService.GetById(id);
            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }

        // POST: Fornecedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var fornecedor = _fornecedorAppService.GetById(id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            _fornecedorAppService.Remove(id);

            return RedirectToAction(nameof(Index));
        }

        private bool FornecedorExists(int id)
        {
            return !(_fornecedorAppService.GetById(id).FornecedorId.ToString() == string.Empty);

        }
    }
}

scr/AGS.ERP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AGS.ERP.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/toastr/css/toastr.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/lib/toastr/css/toastr.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    </environment>

    <script type="text/javascript">
        document.onreadystatechange = function () {
            setTimeout(function () {
                document.getElementById('loader').style.visibility = "hidden";
            }, 1000);
        }
    </script>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AGS.ERP.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a></li>
                    <li><a asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div id="loader">
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AGS.ERP.Web</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/toastr/js/toastr.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/toastr/js/toastr.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>